### ISSUE TITLE
Refactor HRVParameters

### ISSUE THREAD

**Issue by thomcz** [HRVBand/hrv-band#123]
- [x] Rename into Measurement
- [ ] Measurement contains list of HRVParameters 
  - Measurement will contain List of HRVParameter and details (Category, note, rating, ..)

**Comment by Fenox** [comment]
Finde ich gut, könnten wir überlegen ob wir in dem Schritt vlt die Klasse AllHRVCalculator entfernen? 
Ich finde, dass die Klasse sowieso nicht so gut in die Library passt und eigentlich würde die neue Klasse im Android Projekt dann die Aufgabe übernehmen.

**Comment by Fenox** [comment]
ich binde gerade die neue Library ein und ändere dabei etwas hieran.

**Comment by Fenox** [comment]
Current Solution is: HRVParameters are calculated using the Measurement object, the Measurement Object does not store the HRVParameters, it only contains important data about the measurement. 
I think this approach is not that bad because it represents low coupling and high cohesion.

**Comment by thomcz** [comment]
can we close this?
