### ISSUE TITLE
Number To Small Exception in HRVLib

### ISSUE THREAD

**Issue by thomcz** [HRVBand/hrv-band#132]
see: https://github.com/HRVBand/hrv-lib/issues/4

Fix bug in HRVLib

**Comment by Fenox** [comment]
Approach HRV-Lib:
 [ ] Write some further tests for HRV-Lib
 [ ] Implement Error Handling
 [ ] Write tests for Error Handling

Approach HRV-Band:
 [ ] Include new HRV-Lib without much change
 [ ] create view for error handling (probably a popup dialog message)
 [ ] implement minimum and maximum measurement times
 [ ] test & release
