### ISSUE TITLE
Check HRV parameters

### ISSUE THREAD

**Issue by thomcz** [HRVBand/hrv-band#139]
Check the calculated parameters shown in the [MeasuredValueFragment](https://github.com/HRVBand/hrv-band/blob/master/app/src/main/java/hrv/band/app/view/fragment/MeasuredValueFragment.java) and calculated in the [presenter](https://github.com/HRVBand/hrv-band/blob/master/app/src/main/java/hrv/band/app/view/presenter/HRVParameterPresenter.java). 
There are some with no unit (maybe no error) and sd1sd2 is duplicated but with different values (probably an error)

**Comment by Fenox** [comment]
Many parameters don't have a Unit. 
Duplication of SD1SD2 is now fixed in HRV-Lib and hopefully soon in hrv-band...
